name: ci_test_pr

on:
  pull_request:
    branches: [ main ]

jobs:
  # pr to main trigger test
  test:
    runs-on: [self-hosted, Linux, X64, build]
    steps:
    - uses: actions/checkout@v2
    - name: check libgtest 
      run: ls /usr/src/gtest
    - name: Run Test
      run: sh test.sh 0